export const FETCH_RUNS = 'FETCH_RUNS';
export const RUNS_RECEIVED = 'RUNS_RECEIVED';
export const RUNS_ERROR = 'RUNS_ERROR'

export const FETCH_MATCH_RUNS = 'FETCH_MATCH_RUNS';
export const MATCH_RUNS_RECEIVED = 'MATCH_RUNS_RECEIVED';
export const MATCH_RUNS_ERROR = 'MATCH_RUNS_ERROR';

export const FETCH_TIME_DATA = 'FETCH_TIME_DATA';
export const TIME_DATA_RECEIVED = 'TIME_DATA_RECEIVED';
export const TIME_DATA_ERROR = 'TIME_DATA_ERROR';

export const FETCH_BAR_DATA = 'FETCH_BAR_DATA';
export const BAR_DATA_RECEIVED = 'BAR_DATA_RECEIVED';
export const BAR_DATA_ERROR = 'BAR_DATA_ERROR';