export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAILED = 'ADD_DATA_FAILED';

export const READ_DATA_REQUEST = 'READ_DATA_REQUEST';
export const READ_DATA_SUCCESS = 'READ_DATA_SUCCESS';
export const READ_DATA_FAILED = 'READ_DATA_FAILED';
